#!/bin/bash

cmd=$1
url=$2

print() {
    echo GITVAULT: "$@" 1>&2
}

trace() {
    if [ $GITVAULT_TRACE ]; then
        print "$@"
    fi
}

if [ ! $GITVAULT_ENC_OPTIONS ]; then
    if [ ! $GITVAULT_PASSWORD ]; then
        print "You must set GITVAULT_PASSWORD"
        exit
    else
        enc_opts="-aes-128-cbc -pass pass:$GITVAULT_PASSWORD"
    fi
else
    enc_opts=$GITVAULT_ENC_OPTIONS
fi

function encrypt() {
    archive=$(mktemp -t gitvault)

    tar -c -f $archive -C $2 .
    trace "archived: $2 -> $archive"

    openssl enc $enc_opts -in $archive -out $1
    trace "encrypted: $archive -> $1"

    rm $archive
}

function decrypt() {
    archive=$(mktemp -t gitvault)

    openssl enc $enc_opts -in $2 -out $archive -d
    trace "decrypted: $2 -> $archive"

    tar -x -f $archive -C $1
    trace "extracted: $archive -> $1"

    rm $archive
}

if [ ! -f $url ]; then
    trace "creating repo at $url"
    tempdir=$(mktemp -d -t gitvault)
    git init --bare $tempdir >/dev/null
    trace "bare repo init'd at $tempdir"
    encrypt $url $tempdir
    rm -rf $tempdir
fi

tempdir=$(mktemp -d -t gitvault)
decrypt $tempdir $url     && \
    $1 $tempdir           && \
    encrypt $url $tempdir && \
    rm -rf $tempdir
